name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Ensure breakout SVGs are in output directory
        run: |
          if [ -f output/light.svg ]; then echo "light.svg exists"; else echo "light.svg missing"; fi
          if [ -f output/dark.svg ]; then echo "dark.svg exists"; else echo "dark.svg missing"; fi
          # If the files are generated elsewhere, move them here
          # Example: mv path/to/generated/light.svg output/light.svg
          # Example: mv path/to/generated/dark.svg output/dark.svg

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: breakout-output
          commit_message: "Update breakout animation [skip ci]"
